# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FIFAGG' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FIFAGG
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'SnapKit', '5.0.0'
    pod 'Kingfisher', '7.0'
    pod 'Alamofire'
end
